#replicas: 1
testFramework:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
downloadDashboards:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits: {}
initChownData:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
sidecar:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
imageRenderer:
  #replicas: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
