name: projects/core/docker-images/go-sdk
on:
  pull_request:
    paths:
      - "projects/core/docker-images/go-sdk/**"
      - "!projects/core/docker-images/go-sdk/README.md"
  push:
    branches:
      - main
    paths:
      - "projects/core/docker-images/go-sdk/**"
      - "!projects/core/docker-images/go-sdk/README.md"
      - "!projects/core/docker-images/go-sdk/container-structure-test.yaml"
jobs:
  projects-core-docker-images-go-sdk:
    name: projects/core/docker-images/go-sdk
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gogcp-devcontainer:0.1.0
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory /__w/gorun/gorun
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker auth (Google Artifact Registry)
        run: gcloud auth configure-docker "europe-central2-docker.pkg.dev"
      - name: docker auth (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker auth (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: ./scripts/docker-image build "projects/core/docker-images/go-sdk"
      - name: test
        run: ./scripts/docker-image test "projects/core/docker-images/go-sdk"
      - if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        name: pre-publish
        run: ./scripts/docker-image pre-publish "projects/core/docker-images/go-sdk"
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: publish
        run: ./scripts/docker-image publish "projects/core/docker-images/go-sdk"
      - name: show
        run: ./scripts/docker-image show "projects/core/docker-images/go-sdk"
